"""Phase 3 schema additions

Revision ID: 790a59a40b0c
Revises: e1fc1ab09e24
Create Date: 2026-06-17 19:01:01.218756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790a59a40b0c'
down_revision: Union[str, Sequence[str], None] = 'e1fc1ab09e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_match_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_product_name', sa.String(), nullable=False),
    sa.Column('suggested_product_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pending_transaction_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='valid_review_status'),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_match_reviews_id'), 'product_match_reviews', ['id'], unique=False)
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('image_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_transactions_image_hash'), 'transactions', ['image_hash'], unique=False)
    op.create_index(op.f('ix_transactions_product_id'), 'transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_product_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_image_hash'), table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'image_hash')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'updated_at')
    op.drop_index(op.f('ix_product_match_reviews_id'), table_name='product_match_reviews')
    op.drop_table('product_match_reviews')
    # ### end Alembic commands ###
