"""Initial modular schema

Revision ID: e1fc1ab09e24
Revises: 
Create Date: 2026-06-17 18:48:48.515153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fc1ab09e24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'current_stock')
    op.add_column('transactions', sa.Column('invoice_filename', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('raw_ai_response', sa.String(), nullable=True))
    op.alter_column('transactions', 'date_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('transactions', 'raw_ai_response')
    op.drop_column('transactions', 'invoice_filename')
    op.add_column('products', sa.Column('current_stock', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
